default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: planning_poker_development
  # database: planning_poker_prod_backup
  # database: planning_poker_qa_backup
  username: vagrant
  password:

test:
  <<: *default
  database: planning_poker_test
  username: vagrant
  password:
